// packages/x6-react-shape/src/view.ts
import React from 'react'
import ReactDOM from 'react-dom'
import { NodeView, Scheduler } from '@digiforce-cloud/x6'
import { ReactShape } from './node'
import { Portal } from './portal'
import { Wrap } from './wrap'

export class ReactShapeView extends NodeView<ReactShape> {
  protected init() {
    super.init()
    this.cell.on('removed', () => {
      Portal.disconnect(this.cell.id)
    })
  }

  getComponentContainer() {
    return this.cell.prop('useForeignObject') === false
      ? (this.selectors.content as SVGElement)
      : (this.selectors.foContent as HTMLDivElement)
  }

  confirmUpdate(flag: number) {
    const ret = super.confirmUpdate(flag)
    return this.handleAction(ret, ReactShapeView.action, () => {
      if (Scheduler) {
        Scheduler.scheduleTask(() => {
          this.renderReactComponent()
        })
      } else {
        this.renderReactComponent()
      }
    })
  }

  protected renderReactComponent() {
    this.unmountReactComponent()
    const root = this.getComponentContainer()
    const node = this.cell
    const graph = this.graph

    if (root) {
      const component = this.graph.hook.getReactComponent(node)
      const elem = React.createElement(Wrap, { graph, node, component })
      if (Portal.isActive()) {
        Portal.connect(this.cell.id, ReactDOM.createPortal(elem, root))
      } else {
        ReactDOM.render(elem, root)
      }
    }
  }

  protected unmountReactComponent() {
    const root = this.getComponentContainer()
    if (root) {
      ReactDOM.unmountComponentAtNode(root)
    }
    return root
  }

  onMouseDown(e: JQuery.MouseDownEvent, x: number, y: number) {
    const target = e.target as Element
    const tagName = target.tagName.toLowerCase()
    if (tagName === 'input') {
      const type = target.getAttribute('type')
      if (
        type == null ||
        [
          'text',
          'password',
          'number',
          'email',
          'search',
          'tel',
          'url',
        ].includes(type)
      ) {
        return
      }
    }

    super.onMouseDown(e, x, y)
  }

  unmount() {
    Portal.disconnect(this.cell.id)
    this.unmountReactComponent()
    super.unmount()
    return this
  }
}

export namespace ReactShapeView {
  export const action = 'react' as any

  ReactShapeView.config({
    bootstrap: [action],
    actions: {
      component: action,
    },
  })

  NodeView.registry.register('react-shape-view', ReactShapeView, true)
}

// packages/x6-angular-shape/src/view.ts
import {
  ApplicationRef,
  ComponentFactoryResolver,
  TemplateRef,
  ViewContainerRef,
} from '@angular/core'
import { NodeView, Scheduler } from '@digiforce-cloud/x6'
import {
  ComponentPortal,
  DomPortalOutlet,
  TemplatePortal,
} from '@angular/cdk/portal'
import { AngularShape } from './node'

export class AngularShapeView extends NodeView<AngularShape> {
  protected init() {
    super.init()
  }

  getContentContainer() {
    return this.selectors.foContent as HTMLDivElement
  }

  confirmUpdate(flag: number) {
    const ret = super.confirmUpdate(flag)
    return this.handleAction(ret, AngularShapeView.action, () => {
      Scheduler.scheduleTask(() => this.renderAngularContent())
    })
  }

  protected renderAngularContent() {
    this.unmountAngularContent()
    const root = this.getContentContainer()
    if (root) {
      const node = this.cell
      const { injector, content } = this.graph.hook.getAngularContent(node)
      const applicationRef = injector.get(ApplicationRef)
      const viewContainerRef = injector.get(ViewContainerRef)
      const componentFactoryResolver = injector.get(ComponentFactoryResolver)
      const domOutlet = new DomPortalOutlet(
        root,
        componentFactoryResolver,
        applicationRef,
        injector,
      )
      if (content instanceof TemplateRef) {
        const ngArguments =
          (node.data?.ngArguments as { [key: string]: any }) || {}
        const portal = new TemplatePortal(content, viewContainerRef, {
          ngArguments,
        })
        domOutlet.attachTemplatePortal(portal)
      } else {
        const portal = new ComponentPortal(content, viewContainerRef)
        const componentRef = domOutlet.attachComponentPortal(portal)
        // 将用户传入的ngArguments依次赋值到component的属性当中
        const renderComponentInstance = () => {
          const ngArguments =
            (node.data?.ngArguments as { [key: string]: any }) || {}
          Object.keys(ngArguments).forEach(
            (v) => (componentRef.instance[v] = ngArguments[v]),
          )
          componentRef.changeDetectorRef.detectChanges()
        }
        renderComponentInstance()
        // 监听用户调用setData方法
        node.on('change:data', () => renderComponentInstance())
      }
    }
  }

  protected unmountAngularContent() {
    const root = this.getContentContainer()
    root.innerHTML = ''
    return root
  }

  unmount() {
    this.unmountAngularContent()
    super.unmount()
    return this
  }
}

export namespace AngularShapeView {
  export const action = 'angular' as any

  AngularShapeView.config({
    bootstrap: [action],
    actions: {
      component: action,
    },
  })

  NodeView.registry.register('angular-shape-view', AngularShapeView, true)
}
